# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0ZBZuRt4

  sftp:
    image: atmoz/sftp
    volumes:
    - /home/ilyasziyaoglu/cdn:/home/mercadeo/cdn
    ports:
      - "2222:22"
    command: mercadeo:mercadeo:1001

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
